### ISSUE TITLE
WGS parameter question 

### ISSUE THREAD

**Issue by lawtyunc** [TheJacksonLaboratory/cs-nf-pipelines#10]
Hello I just had a quick question about the WGS pipeline. 
As far as the --dbSNP and --dbSNFP goes, is dbSNFP used only for humans or is this a parameter that should also be used for mice samples ? Also, should both dbSNP and --dbSNFP be used for mice  and if so, are the files suppose to be the same like it shows in the
github page?

--dbSNP

Default: '/projects/omics_share/mouse/GRCm38/genome/annotation/snps_indels/GCA_000001635.6_current_ids.vcf.gz'

--dbNSFP

Default: '/projects/omics_share/mouse/GRCm38/genome/annotation/snps_indels/GCA_000001635.6_current_ids.vcf.gz'

**Comment by MikeWLloyd** [comment]
`dbNSFP` is used only in the human workflow. We have corrected the typo in the documentation.
