### ISSUE TITLE
Using Pseudo reference Pipeline 

### ISSUE THREAD

**Issue by lawtyunc** [TheJacksonLaboratory/cs-nf-pipelines#11]
Hello All,
So I had a question in reference to using Pseudo reference pipeline. If not using default Mouse strains given in the GBRS pipeline and I have put these below. I understand that other mouse strain reference files would have to be generated. Could yall explain a little bit of how this works and how then those files would be incorporated back into the GBRS pipeline? Do you just provide a string for the specific strains you want in the --strain param? does this pull from a data base to ref that strain and then does the output of the pipeline create a file that would need to go back into GBRS? Also do you not have to specify C57BL/6J?( since there should be 8 strains total)
A/J 
C57BL/6J 
129S1/Svlmj 
NOD/ShiLtj 
NZO/HILtj
CAST/Eij 
PWK/Phj 
WSB/EiJ

**Comment by MikeWLloyd** [comment]
To generate inputs for GBRS for different strains there are a number of steps you must complete. 

1. Regenerate pseudo-references.
2. Build a multi-way transcriptome.
3. Run EMASE against founder data of your strains to provide input used in re-training the emission probability model.
4. Re-train the emission probability model
5. Generate transition probabilities and other required GBRS inputs based on your strains and transcript annotation version. 

These steps are wrapped into the following workflows and script: 

- `--workflow generate_pseudoreference`
- `--workflow prepare_emase`
- `--workflow emase`
- `bin/gbrs/generate_emission_prob_avecs.py` 
This script will require an input csv file that defines samples based on the IDs used in prior steps (e.g., A, B, C, ...). 

> ```
> sampleID,tissue,strain,DO_id,sex,exclude
> 129_1_Adipose,Adipose,129S1_SvImJ,C,F,NO
> ```

- `--workflow prep_do_gbrs_inputs`

With the exception of the python script, additional information for all can be found in the respective wiki for each.
