### ISSUE TITLE
gbrs_emissions_all_tissues.avecs.npz output file question

### ISSUE THREAD

**Issue by lawtyunc** [TheJacksonLaboratory/cs-nf-pipelines#16]
Hi Jackson Lab,
I was looking at the output of the the gbrs_emissions_all_tissues.avecs.npz file and I wanted to make sure I was understanding this correctly? Correct me on this if I am wrong because I am new to emission probability but in this file, is it basically the header or name is 
 the gene and for each gene there is an array of numbers and each one represents the  probability  for the  haplotype or mouse strain associated with that gene? Also, are there several arrays for one specific gene because it is showing all of the possible combinations and predictions based on the Hidden Markov model?

**Comment by MikeWLloyd** [comment]
@lawtyunc your questions fall outside the scope of issues we support in this repository. Your statements seem correct, but I suggest contacting the GBRS developers for confirmation and any further questions related to GBRS.
