### ISSUE TITLE
WGS pipeline error

### ISSUE THREAD

**Issue by lawtyunc** [TheJacksonLaboratory/cs-nf-pipelines#7]
Hi Jackson Lab,
I was running your cs-nf-WGS pipeline and getting the following error

ERROR ~ Error executing process > 'WGS:BWA_MEM (S*)'

Caused by:
  Process `WGS:BWA_MEM

Command executed:

  rg=$(cat S*read_group.txt)
  bwa mem -R ${rg}   -t 12  -B 8  path/to/Mus_musculus.GRCm39.dna.toplevel.fa.fai

the confusing part is the input wants a `fasta index` file but in the documentation is asking for a fasta file wasn't sure if this was a typo or how  we could get around this error? 

--ref_fa_indices

Default: '/projects/omics_share/mouse/GRCm38/genome/indices/ensembl/v102/bwa/Mus_musculus.GRCm38.dna.toplevel.fa'
Comment: Pre-compiled BWA index files, points to human reference when * --gen_org human. JAX users should not change this parameter.

**Comment by MikeWLloyd** [comment]
`ref_fa_indices` should point to BWA index files and not the `.fai` file.

Generate BWA indecies with the tool (i.e., `bwa index ref.fa`) and then set `ref_fa_indices` to the path and base file name of the index files.
